### ISSUE TITLE
Config additional aliases

### ISSUE THREAD

**Issue by BartosB13** [Tweetzy/Markets#95]
**Describe Feature**
In the plugin configuration or somewhere else there would be an option that would allow you to add alternative versions of commands and subcommands.

Maybe it could also work on the principle of separate "trees" of commands for languages ​​- i.e. using the main command in English will display subcommands in the same language. And for example for Spanish, the Spanish subcommands would be tabulated.
Whereby all options would always work, regardless of the language (i.e. only tabbing would be sorted in the trees somehow)

Below I show an example of such an option, adding aliases for the main command:

```
#In this case main = /markets
Aliases:
  main:
    - "shops"
    - "player_shops"
    - "market"
  subcommands:
    Bank:
      - "deposit"
      - "shop_bank"
```

And here is an extended example for multi-language support:

```
#In this case main = /markets
Aliases:
  main:
    en_us:
      - "shops"
      - "player_shops"
      - "market"
    <other_language>:
      - "1"
      - "2"
      - "3"
  subcommands:
    Bank:
      en_us:
        - "deposit"
        - "shop_bank"
      <other_language>:
        - "1"
```
